{{ if and (index .Values "modules" "text2vec-voyageai" "enabled") (index .Values "modules" "text2vec-voyageai" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-voyageai
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-voyageai" "apiKey" | b64enc }}
{{ end }}
