{{ if and (index .Values "modules" "text2vec-jinaai" "enabled") (index .Values "modules" "text2vec-jinaai" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-jinaai
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-jinaai" "apiKey" | b64enc }}
{{ end }}
